#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

src=$(readlink -f ../../../src)
make -C $src clean > /dev/null
make -C $src -j8 X=$tmp/bin/nfqlb static > /dev/null || die make

$XCLUSTER install_prog --dest=$tmp jq

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
