#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

src=$(readlink -f $dir/../../../src)
make -C $src clean > /dev/null
make -C $src -j8 X=$tmp/bin/nfqlb $MAKEOPT > /dev/null || die make

for x in mconnect ctraffic; do
	f=$GOPATH/src/github.com/Nordix/$x/image/$x
	if test -x $f; then
		log "Using local [$x]"
		cp $f $tmp/bin
	else
		ar=$ARCHIVE/$x.xz
		if test -r $ar; then
			unpack=xz
		else
			ar=$ARCHIVE/$x.gz			
			test -r $ar || die "Not found [$x]"
			unpack=gzip
		fi
		$unpack -dc $ar > $tmp/bin/$x
		chmod a+x $tmp/bin/$x
	fi
done

$XCLUSTER install_prog --dest=$tmp jq

if test "$xcluster_HW_SETUP" = "yes"; then
	iperf=$HOME/Downloads/iperf
	test -x $iperf || die "Not executable [$iperf]"
	mkdir -p $tmp/root/Downloads
	cp $iperf $tmp/root/Downloads
	cp $dir/../../../nfqlb.sh $dir/../../nfqlb_performance.sh $tmp/bin
	rm $tmp/etc/init.d/20load-balancer.rc $tmp/etc/init.d/50nfqueue.rc
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
